product = [
    {
        '_id' : '1',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
    {
        '_id' : '2',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
    {
        '_id' : '3',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
    {
        '_id' : '4',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
    {
        '_id' : '5',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
    {
        '_id' : '6',
        'name' : 'Airpods pro',
        'description' : 'An apple product',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 180,
    },
]